services:
  leetcode_redis:
    image: redis:7.2.5
    restart: always
    ports:
      - '6380:6379'
    environment:
      - REDIS_PORT=6379
  db:
    image: postgres:16.3
    restart: always
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: example
  rabbitmq:
    image: rabbitmq:3.13.3
    ports:
      - '5671:5671'
      - '5672:5672'
      - '15674:15674'
      - '15672:15672'
    volumes:
      - ./config/rabbitmq/rabbitmq-oauth.conf:/etc/rabbitmq/conf.d/rabbitmq-oauth.conf
      - ./config/rabbitmq/certs/public.pem:/etc/rabbitmq/certs/oauth-public.pem
    env_file: './config/rabbitmq/docker.env'
    command: >
      bash -c "rabbitmq-plugins enable --offline \
      rabbitmq_management \
      rabbitmq_stomp \
      rabbitmq_web_stomp \
      rabbitmq_auth_backend_oauth2 \
      && rabbitmq-server restart"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5672']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
