services:
  leetcode_redis:
    image: redis:7.2.5
    restart: always
    ports:
      - '6380:6379'
    environment:
      - REDIS_PORT=6379
  db:
    image: postgres:16.3
    restart: always
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: example
